# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pet.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(136, 94)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/image/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 131, 91))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pet = QtWidgets.QLabel(self.frame)
        self.pet.setGeometry(QtCore.QRect(50, 10, 80, 80))
        self.pet.setText("")
        self.pet.setPixmap(QtGui.QPixmap(":/icon/image/icon.png"))
        self.pet.setScaledContents(True)
        self.pet.setObjectName("pet")
        self.item = QtWidgets.QLabel(self.frame)
        self.item.setGeometry(QtCore.QRect(10, 30, 48, 48))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.item.setFont(font)
        self.item.setText("")
        self.item.setPixmap(QtGui.QPixmap(":/image/image/cookie.png"))
        self.item.setScaledContents(True)
        self.item.setObjectName("item")
        self.pet_2 = QtWidgets.QLabel(self.frame)
        self.pet_2.setGeometry(QtCore.QRect(60, 20, 51, 51))
        self.pet_2.setText("")
        self.pet_2.setPixmap(QtGui.QPixmap(":/face/image/face_happy.png"))
        self.pet_2.setScaledContents(True)
        self.pet_2.setObjectName("pet_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Pet"))
import test_rc
